Repository ripe-tech/dhl-api-js, pull requests merged in 2022-04, with the labels that each got.

#17 doc: added documentation to API methods
  README.md
  js/pickup.js
  js/shipment.js
  js/tracking.js
Labels: documentation, no-changelog

#18 feat: more service codes and taxable services
  CHANGELOG.md
  js/shipment.js
Labels: enhancement

#19 version: 0.6.2
  CHANGELOG.md
  package.json
Labels: release 🎉
